import { hasFlag } from "country-flag-icons";

const FLAG_CDN_BASE = "https://purecatamphetamine.github.io/country-flag-icons/3x2";

/** 리그 이름 앞 부분(국가/지역) → ISO 3166-1 alpha-2 국가 코드 (country-flag-icons 지원) */
const LEAGUE_TO_COUNTRY: Record<string, string> = {
  // World / International
  world: "__WORLD__",
  worldwide: "__WORLD__",
  international: "__WORLD__",
  europe: "EU",
  european: "EU",
  // Americas
  usa: "US",
  "united states": "US",
  us: "US",
  america: "US",
  american: "US",
  canada: "CA",
  canadian: "CA",
  mexico: "MX",
  mexican: "MX",
  brazil: "BR",
  brazilian: "BR",
  argentina: "AR",
  argentine: "AR",
  argentinian: "AR",
  chile: "CL",
  chilean: "CL",
  colombia: "CO",
  colombian: "CO",
  peru: "PE",
  peruvian: "PE",
  uruguay: "UY",
  uruguayan: "UY",
  ecuador: "EC",
  ecuadorian: "EC",
  venezuela: "VE",
  venezuelan: "VE",
  paraguay: "PY",
  paraguayan: "PY",
  bolivia: "BO",
  bolivian: "BO",
  "costa rica": "CR",
  "costa rican": "CR",
  panama: "PA",
  panamanian: "PA",
  honduras: "HN",
  honduran: "HN",
  guatemala: "GT",
  guatemalan: "GT",
  salvador: "SV",
  "el salvador": "SV",
  salvadoran: "SV",
  nicaragua: "NI",
  nicaraguan: "NI",
  cuba: "CU",
  cuban: "CU",
  jamaica: "JM",
  jamaican: "JM",
  trinidad: "TT",
  tobago: "TT",
  "trinidad and tobago": "TT",
  "puerto rico": "PR",
  dominican: "DO",
  "dominican republic": "DO",
  // Europe - Western
  england: "GB-ENG",
  english: "GB-ENG",
  uk: "GB",
  britain: "GB",
  british: "GB",
  scotland: "GB-SCT",
  scottish: "GB-SCT",
  wales: "GB-WLS",
  welsh: "GB-WLS",
  "northern ireland": "GB-NIR",
  ireland: "IE",
  irish: "IE",
  france: "FR",
  french: "FR",
  germany: "DE",
  german: "DE",
  spain: "ES",
  spanish: "ES",
  catalonia: "ES-CT",
  catalan: "ES-CT",
  italy: "IT",
  italian: "IT",
  netherlands: "NL",
  dutch: "NL",
  holland: "NL",
  belgium: "BE",
  belgian: "BE",
  portugal: "PT",
  portuguese: "PT",
  switzerland: "CH",
  swiss: "CH",
  austria: "AT",
  austrian: "AT",
  greece: "GR",
  greek: "GR",
  turkey: "TR",
  turkish: "TR",
  // Europe - Northern
  sweden: "SE",
  swedish: "SE",
  norway: "NO",
  norwegian: "NO",
  denmark: "DK",
  danish: "DK",
  finland: "FI",
  finnish: "FI",
  iceland: "IS",
  icelandic: "IS",
  // Europe - Eastern
  russia: "RU",
  russian: "RU",
  poland: "PL",
  polish: "PL",
  ukraine: "UA",
  ukrainian: "UA",
  czech: "CZ",
  "czech republic": "CZ",
  czechia: "CZ",
  slovakia: "SK",
  slovak: "SK",
  hungary: "HU",
  hungarian: "HU",
  romania: "RO",
  romanian: "RO",
  bulgaria: "BG",
  bulgarian: "BG",
  croatia: "HR",
  croatian: "HR",
  serbia: "RS",
  serbian: "RS",
  bosnia: "BA",
  "bosnia and herzegovina": "BA",
  bosnian: "BA",
  slovenia: "SI",
  slovenian: "SI",
  montenegro: "ME",
  macedonia: "MK",
  "north macedonia": "MK",
  macedonian: "MK",
  albania: "AL",
  albanian: "AL",
  kosovo: "XK",
  estonia: "EE",
  estonian: "EE",
  latvia: "LV",
  latvian: "LV",
  lithuania: "LT",
  lithuanian: "LT",
  belarus: "BY",
  belarusian: "BY",
  moldova: "MD",
  moldovan: "MD",
  georgia: "GE",
  georgian: "GE",
  armenia: "AM",
  armenian: "AM",
  azerbaijan: "AZ",
  azerbaijani: "AZ",
  cyprus: "CY",
  cypriot: "CY",
  malta: "MT",
  maltese: "MT",
  luxembourg: "LU",
  luxembourgish: "LU",
  monaco: "MC",
  // Asia
  china: "CN",
  chinese: "CN",
  japan: "JP",
  japanese: "JP",
  "south korea": "KR",
  "korea republic": "KR",
  korean: "KR",
  "north korea": "KP",
  india: "IN",
  indian: "IN",
  australia: "AU",
  australian: "AU",
  thailand: "TH",
  thai: "TH",
  vietnam: "VN",
  vietnamese: "VN",
  malaysia: "MY",
  malaysian: "MY",
  singapore: "SG",
  singaporean: "SG",
  indonesia: "ID",
  indonesian: "ID",
  philippines: "PH",
  filipino: "PH",
  "philippine": "PH",
  taiwan: "TW",
  taiwanese: "TW",
  hong: "HK",
  "hong kong": "HK",
  macau: "MO",
  macao: "MO",
  "sri lanka": "LK",
  srilankan: "LK",
  bangladesh: "BD",
  bangladeshi: "BD",
  pakistan: "PK",
  pakistani: "PK",
  nepal: "NP",
  nepalese: "NP",
  myanmar: "MM",
  burma: "MM",
  burmese: "MM",
  cambodia: "KH",
  cambodian: "KH",
  laos: "LA",
  laotian: "LA",
  mongolia: "MN",
  mongolian: "MN",
  kazakhstan: "KZ",
  kazakh: "KZ",
  uzbekistan: "UZ",
  uzbek: "UZ",
  tajikistan: "TJ",
  tajik: "TJ",
  kyrgyzstan: "KG",
  kyrgyz: "KG",
  turkmenistan: "TM",
  turkmen: "TM",
  // Middle East
  "saudi arabia": "SA",
  saudi: "SA",
  uae: "AE",
  "united arab emirates": "AE",
  emirates: "AE",
  emirati: "AE",
  qatar: "QA",
  qatari: "QA",
  iran: "IR",
  iranian: "IR",
  iraq: "IQ",
  iraqi: "IQ",
  israel: "IL",
  israeli: "IL",
  jordan: "JO",
  jordanian: "JO",
  lebanon: "LB",
  lebanese: "LB",
  syria: "SY",
  syrian: "SY",
  yemen: "YE",
  yemeni: "YE",
  oman: "OM",
  omani: "OM",
  kuwait: "KW",
  kuwaiti: "KW",
  bahrain: "BH",
  bahraini: "BH",
  palestine: "PS",
  palestinian: "PS",
  // Africa
  egypt: "EG",
  egyptian: "EG",
  morocco: "MA",
  moroccan: "MA",
  tunisia: "TN",
  tunisian: "TN",
  algeria: "DZ",
  algerian: "DZ",
  "south africa": "ZA",
  "south african": "ZA",
  nigerian: "NG",
  nigeria: "NG",
  kenya: "KE",
  kenyan: "KE",
  ghana: "GH",
  ghanian: "GH",
  ghanaian: "GH",
  senegal: "SN",
  senegalese: "SN",
  "ivory coast": "CI",
  "cote d'ivoire": "CI",
  ivoire: "CI",
  cameroon: "CM",
  cameroonian: "CM",
  drc: "CD",
  "drc congo": "CD",
  "democratic republic of congo": "CD",
  congo: "CG",
  congolese: "CG",
  ethiopia: "ET",
  ethiopian: "ET",
  tanzania: "TZ",
  tanzanian: "TZ",
  uganda: "UG",
  ugandan: "UG",
  zimbabwe: "ZW",
  zimbabwean: "ZW",
  zambia: "ZM",
  zambian: "ZM",
  angola: "AO",
  angolan: "AO",
  mozambique: "MZ",
  mozambican: "MZ",
  mali: "ML",
  malian: "ML",
  malawi: "MW",
  malawian: "MW",
  madagascar: "MG",
  malagasy: "MG",
  libya: "LY",
  libyan: "LY",
  sudan: "SD",
  sudanese: "SD",
  mauritius: "MU",
  mauritian: "MU",
  botswana: "BW",
  namibia: "NA",
  rwanda: "RW",
  rwandan: "RW",
  burundi: "BI",
  burundian: "BI",
  // Oceania
  "new zealand": "NZ",
  zealand: "NZ",
  "new zealander": "NZ",
  fiji: "FJ",
  fijian: "FJ",
  "papua new guinea": "PG",
  papua: "PG",
  "solomon islands": "SB",
};

/** World/국제 대회용 글로브 아이콘 (로컬) */
const WORLD_ICON_URL = "/icons/globe.svg";

/** 리그 이름에서 국가/지역 키워드 추출 후 ISO 국가 코드 또는 __WORLD__ 반환 */
function getLeagueCode(leagueName: string): string | null {
  if (!leagueName?.trim()) return null;
  const lower = leagueName.trim().toLowerCase();
  const candidates = [
    lower.split(".")[0]?.trim(),
    lower.split(" - ")[0]?.trim(),
    lower.split("-")[0]?.trim(),
  ].filter(Boolean) as string[];
  candidates.push(lower.replace(/\s+/g, " "));
  const words = lower.split(/[\s.\-_,;]+/).filter((w) => w.length >= 2);
  candidates.push(...words);
  for (const key of candidates) {
    const code = LEAGUE_TO_COUNTRY[key];
    if (!code) continue;
    if (code === "__WORLD__") return code;
    if (hasFlag(code)) return code;
  }
  return null;
}

/** 리그 이름에서 country-flag-icons CDN 국기 URL 반환 (World/국제는 글로브 아이콘, 없으면 null) */
export function getLeagueFlagUrl(leagueName: string): string | null {
  const code = getLeagueCode(leagueName);
  if (!code) return null;
  if (code === "__WORLD__") return WORLD_ICON_URL;
  return `${FLAG_CDN_BASE}/${code}.svg`;
}
